---
version: "4.0.0"

services:
  headscale:
    container_name: headscale
    build: .
    ports:
      - 443:8080
  
  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 9080:80
